name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: DEV

    env:
      DATABRICKS_AUTH_TYPE: github-oidc
      DATABRICKS_HOST: https://dbc-9ed413ac-d791.cloud.databricks.com
      DATABRICKS_CLIENT_ID:b2a6ac45-76a0-4686-8f73-824d69dbca47

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Who is logged in?
        run: databricks current-user me

      - name: Validate bundle
        run: databricks bundle validate --target dev

      - name: Deploy bundle
        run: databricks bundle deploy --target dev